### ISSUE TITLE
How do I work on Window10.

### ISSUE THREAD

**Issue by fredhwang** [tavurth/godot-gdscript-obfuscator#5]
I put this script in my game directory.
K:\Project\WBM
There are game gd scripts.

and I installed python3 on my windows.
and I excuted  " python3 obfuscator.py "
-----------------------------------
K:\Project\WBM>python3 obfuscate.py
Traceback (most recent call last):
  File "K:\Project\WBM\obfuscate.py", line 3, in <module>
    from obfuscator import obfuscate
  File "K:\Project\WBM\obfuscator\__init__.py", line 3, in <module>
    from .obfuscate import obfuscate
  File "K:\Project\WBM\obfuscator\obfuscate.py", line 5, in <module>
    from lark import Tree, Token
ModuleNotFoundError: No module named 'lark'
---------------------------------------
so,
K:\Project\WBM>pip install lark
Collecting lark
  Downloading lark-1.1.5-py3-none-any.whl (107 kB)
     ---------------------------------------- 108.0/108.0 kB 6.1 MB/s eta 0:00:00
Installing collected packages: lark
Successfully installed lark-1.1.5

Again,
K:\Project\WBM>python3 obfuscate.py
'pt' error..

How do solve this??
How can I do this script?

**Comment by tavurth** [comment]
Hi this project was not really ready for production use and was more used as a way to show what might be possible.

Please do not attempt to use this to mangle your project files 🙏
